// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAirwyGkJ6uIpzk_n2EFdku8mmxW2JRT08',
    appId: '1:208519200949:web:a760b09ee79043cc64fefc',
    messagingSenderId: '208519200949',
    projectId: 'servipak-1',
    authDomain: 'servipak-1.firebaseapp.com',
    storageBucket: 'servipak-1.firebasestorage.app',
    measurementId: 'G-3K8Z0TB6E9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdQiCrFge6Y9me6M_9c_gGE31N_moWHaU',
    appId: '1:208519200949:android:28e0d08fed06ab3c64fefc',
    messagingSenderId: '208519200949',
    projectId: 'servipak-1',
    storageBucket: 'servipak-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw3ndANni42-pUJpeZ6W_oliEh6ZpK4zI',
    appId: '1:208519200949:ios:aaa6ac6e585d8e4364fefc',
    messagingSenderId: '208519200949',
    projectId: 'servipak-1',
    storageBucket: 'servipak-1.firebasestorage.app',
    iosBundleId: 'com.example.servipak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw3ndANni42-pUJpeZ6W_oliEh6ZpK4zI',
    appId: '1:208519200949:ios:aaa6ac6e585d8e4364fefc',
    messagingSenderId: '208519200949',
    projectId: 'servipak-1',
    storageBucket: 'servipak-1.firebasestorage.app',
    iosBundleId: 'com.example.servipak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAirwyGkJ6uIpzk_n2EFdku8mmxW2JRT08',
    appId: '1:208519200949:web:8aac63cbeddd695364fefc',
    messagingSenderId: '208519200949',
    projectId: 'servipak-1',
    authDomain: 'servipak-1.firebaseapp.com',
    storageBucket: 'servipak-1.firebasestorage.app',
    measurementId: 'G-L6KYKY65Q2',
  );
}
